// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpgradePlanner.Api.Data;

#nullable disable

namespace UpgradePlanner.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("UpgradePlanner.Api.Models.Upgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrerequisiteUpgradeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductLink")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchasedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisiteUpgradeId");

                    b.ToTable("Upgrades", t =>
                        {
                            t.HasCheckConstraint("CK_Upgrade_Priority", "Priority BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("UpgradePlanner.Api.Models.Upgrade", b =>
                {
                    b.HasOne("UpgradePlanner.Api.Models.Upgrade", "PrerequisiteUpgrade")
                        .WithMany("DependentUpgrades")
                        .HasForeignKey("PrerequisiteUpgradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrerequisiteUpgrade");
                });

            modelBuilder.Entity("UpgradePlanner.Api.Models.Upgrade", b =>
                {
                    b.Navigation("DependentUpgrades");
                });
#pragma warning restore 612, 618
        }
    }
}
